/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package IO;

import IO.Modificacion;
import DAO.CoberturaDAO;
import DAO.CuotaDAO;
import DAO.ImpuestoDAO;
import DAO.ProvinciaDAO;
import DAO.RamoDAO;
import Entity.Cober;
import Entity.Cobertura;
import Entity.Cuota;
import Entity.Provincia;
import Entity.Ramo;
import java.awt.Graphics2D;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Sebastian
 */
public class Principal extends javax.swing.JFrame implements Printable {
private static LinkedList listaCoberturas = new LinkedList();
private DefaultTableModel mode;
private List<String> Clausulas= new ArrayList<String>();
private double totalSumas=0;
private double totalPrimas=0;
private double Sellado=0;
private double Subtotal=0;

    public static void setListaCoberturas(LinkedList listaCoberturas) {
        Principal.listaCoberturas = listaCoberturas;
    }
int con;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        mode=(DefaultTableModel) this.TCoberturas.getModel();
        TableColumnModel columnModel = this.TCoberturas.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(100);

        DefaultComboBoxModel v =new DefaultComboBoxModel();
        this.cmbCobertura.setModel(v);
        v.addElement("Seleccione");
    
        this.cmbCuotas.setVisible(false);
        this.lblCuotas.setVisible(false);
        DefaultComboBoxModel PValue = new DefaultComboBoxModel();
        this.cmbProvincia.setModel(PValue);
        PValue.addElement("Seleccione");
        ProvinciaDAO pDAO= new ProvinciaDAO();
    try {
        List <Provincia> lProvincia = pDAO.ObtenerProvincia();
        for (int i=0;i<lProvincia.size();i++){
            
            PValue.addElement(lProvincia.get(i));
            
        }
        
    } catch (Exception ex) {
        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
        
       DefaultComboBoxModel value = new DefaultComboBoxModel();
        this.cmbRamo.setModel(value);
        value.addElement("Seleccione");
                 
        
         RamoDAO rDAO=new RamoDAO();
            try {
                List <Ramo> lista= rDAO.ObtenerRamo();
                for (int i=0;i<lista.size();i++){                   
                
                    value.addElement(lista.get(i).getNumero());
                
             }
                
            } catch (Exception ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        LimpiarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        cmbRamo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lblRamo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCoberturas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSumaAsegurada = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTasa = new javax.swing.JTextField();
        txtDesde = new javax.swing.JFormattedTextField();
        txtHasta = new javax.swing.JFormattedTextField();
        cmbCobertura = new javax.swing.JComboBox();
        cmbAjustedeTasa = new javax.swing.JComboBox();
        cmbAjusteMensual = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lblTotalPrima = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblTotalSumas = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbMediodePago = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        lblPrimaconRecargoFinanciero = new javax.swing.JLabel();
        lblCuotas = new javax.swing.JLabel();
        cmbCuotas = new javax.swing.JComboBox();
        btnImprimir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        lblClausulas = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbRes = new javax.swing.JComboBox();
        lblResolTotal = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblPrimamasResol = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblImpuestos = new javax.swing.JLabel();
        lblSellados = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblPremio = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbIVA = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        txtAsegurable = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cotizador");

        jLabel1.setText("Desde");

        jLabel2.setText("Hasta");

        jLabel3.setText("Dias:");

        lblDias.setText("0");

        cmbRamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRamoActionPerformed(evt);
            }
        });

        jLabel5.setText("Ramo:");

        lblRamo.setText("---------");

        TCoberturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cobertura", "Suma asegurada", "Tasa", "Ajuste de tasa", "Prima", "Provincia"
            }
        ));
        jScrollPane1.setViewportView(TCoberturas);

        jLabel4.setText("Cobertura");

        jLabel7.setText("Ajuste de tasa");

        jLabel8.setText("Suma asegurada");

        txtSumaAsegurada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSumaAseguradaActionPerformed(evt);
            }
        });

        jLabel9.setText("Tasa");

        txtDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDesde.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDesdeCaretUpdate(evt);
            }
        });
        txtDesde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDesdeFocusLost(evt);
            }
        });

        txtHasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtHasta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHastaFocusLost(evt);
            }
        });

        cmbCobertura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cmbAjustedeTasa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin ajuste", "1%", "2%" }));
        cmbAjustedeTasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAjustedeTasaActionPerformed(evt);
            }
        });

        cmbAjusteMensual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No aplica" }));

        jLabel6.setText("Ajuste mensual");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel10.setText("Total primas:");

        lblTotalPrima.setText("--");

        jLabel11.setText("Total sumas:");

        lblTotalSumas.setText("--");

        jLabel12.setText("Medio de pago");

        cmbMediodePago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contado", "Efectivo", "Tarjeta" }));
        cmbMediodePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMediodePagoActionPerformed(evt);
            }
        });

        jLabel13.setText("Prima con recargo financiero:");

        lblPrimaconRecargoFinanciero.setText("--");

        lblCuotas.setText("Cuotas");

        cmbCuotas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuotasActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel14.setText("Provincia");

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cmbProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvinciaActionPerformed(evt);
            }
        });

        jLabel15.setText("Clausulas");

        lblClausulas.setText("--");

        jLabel16.setText("VAR. RESOL. 32080:");

        cmbRes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-15%", "-14%", "-13%", "-12%", "-11%", "-10%", "-9%", "-8%", "-7%", "-6%", "-5%", "-4%", "-3%", "-2%", "-1%", "0%", "1%", "2%", "3%", "4%", "5%", "6%", "7%", "8%", "9%", "10%" }));
        cmbRes.setSelectedIndex(15);
        cmbRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbResActionPerformed(evt);
            }
        });

        lblResolTotal.setText("--");

        jLabel17.setText("Prima del seguro:");

        lblPrimamasResol.setText("--");

        jLabel18.setText("Impuestos:");

        jLabel19.setText("Sellados:");

        jLabel20.setText("IVA:");

        jLabel21.setText("Premio sin IIBB:");

        lblImpuestos.setText("--");

        lblSellados.setText("--");

        lblIVA.setText("--");

        lblPremio.setText("--");

        jLabel22.setText("IVA");

        cmbIVA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "21%", "24%" }));
        cmbIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIVAActionPerformed(evt);
            }
        });

        jLabel23.setText("Asegurable:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbRamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(lblRamo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel7))
                                                .addGap(3, 3, 3))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbAjusteMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cmbCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbAjustedeTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(8, 8, 8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblDias)
                                            .addGap(197, 197, 197))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtAsegurable, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbProvincia, 0, 100, Short.MAX_VALUE)
                                            .addComponent(txtTasa)
                                            .addComponent(txtSumaAsegurada))
                                        .addGap(65, 65, 65)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(231, 231, 231)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel21)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(189, 189, 189)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel13))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrimaconRecargoFinanciero)
                                    .addComponent(lblPrimamasResol)
                                    .addComponent(lblImpuestos)
                                    .addComponent(lblSellados)
                                    .addComponent(lblIVA)
                                    .addComponent(lblPremio)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(lblCuotas)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMediodePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblClausulas)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalPrima))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(82, 82, 82)
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblResolTotal))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(119, 119, 119)
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblTotalSumas)
                                            .addGap(31, 31, 31))))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbRamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRamo)
                    .addComponent(jLabel23)
                    .addComponent(txtAsegurable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(lblDias)
                            .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtSumaAsegurada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbAjustedeTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbAjusteMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblClausulas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cmbMediodePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCuotas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblTotalSumas))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblTotalPrima))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(lblResolTotal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblPrimamasResol)
                    .addComponent(jLabel22)
                    .addComponent(cmbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblPrimaconRecargoFinanciero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblImpuestos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblSellados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblPremio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSumaAseguradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSumaAseguradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSumaAseguradaActionPerformed

    private void txtDesdeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDesdeCaretUpdate
      
    }//GEN-LAST:event_txtDesdeCaretUpdate

    private void txtDesdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDesdeFocusLost
        
        if((!this.txtHasta.getText().equals("")) && (!this.txtDesde.getText().equals(""))){
            String D=this.txtDesde.getText();
            String DDia=D.substring(0, 2);
            String DMes=D.substring(3, 5);
            String DAño=D.substring(6);
//            this.txtSumaAsegurada.setText(DDia);
//            this.txtTasa.setText(DMes);
//            this.txt.setText(DAño);
            String H=this.txtHasta.getText();
            String HDia=H.substring(0, 2);
            String HMes=H.substring(3, 5);
            String HAño=H.substring(6);
            
          Date desde= new Date(Integer.parseInt(DAño), Integer.parseInt(DMes), Integer.parseInt(DDia));
          Date hasta= new Date(Integer.parseInt(HAño), Integer.parseInt(HMes), Integer.parseInt(HDia));
          
          long res = hasta.getTime()-desde.getTime();
            
        this.lblDias.setText(String.valueOf(res/(1000*60*60*24)));
      }
    }//GEN-LAST:event_txtDesdeFocusLost

    private void txtHastaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHastaFocusLost
        // TODO add your handling code here:
        if((!this.txtHasta.getText().equals("")) && (!this.txtDesde.getText().equals(""))){
            String D=this.txtDesde.getText();
            String DDia=D.substring(0, 2);
            String DMes=D.substring(3, 5);
            String DAño=D.substring(6);
//            this.txtSumaAsegurada.setText(DDia);
//            this.txtTasa.setText(DMes);
//            this.txt.setText(DAño);
            String H=this.txtHasta.getText();
            String HDia=H.substring(0, 2);
            String HMes=H.substring(3, 5);
            String HAño=H.substring(6);
            
          Date desde= new Date(Integer.parseInt(DAño), Integer.parseInt(DMes), Integer.parseInt(DDia));
          Date hasta= new Date(Integer.parseInt(HAño), Integer.parseInt(HMes), Integer.parseInt(HDia));
          
          long res = hasta.getTime()-desde.getTime();
            
        this.lblDias.setText(String.valueOf(res/(1000*60*60*24)));
      }
    }//GEN-LAST:event_txtHastaFocusLost

    private void cmbRamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRamoActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel v =new DefaultComboBoxModel();
        this.cmbCobertura.setModel(v);
        v.addElement("Seleccione");
        if (this.cmbRamo.getSelectedIndex()!=0){
            listaCoberturas.removeAll(listaCoberturas);
            LimpiarTabla();
            RamoDAO rDAO=new RamoDAO();
            try {
                List <Ramo> lista= rDAO.ObtenerRamo();
                for (int i=0;i<lista.size();i++){                   
                if (lista.get(i).getNumero().equals(String.valueOf(this.cmbRamo.getSelectedItem()))){
                    this.lblRamo.setText(lista.get(i).getNombre());
                    
                  CoberturaDAO cDAO=new CoberturaDAO();
                  List <Cober> lcober = cDAO.ObtenerCobertura(lista.get(i).getNumero());
        
                  for (int j=0;j<lcober.size();j++){
        
                   v.addElement(lcober.get(j));
       
                  }  
                    
                }
             }
              
        
                   
//                
            } catch (Exception ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
        this.lblRamo.setText("--");
        }
    }//GEN-LAST:event_cmbRamoActionPerformed

    private void cmbAjustedeTasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAjustedeTasaActionPerformed
        // TODO add your handling code here:
       if (this.cmbAjustedeTasa.getSelectedIndex()==0){
       DefaultComboBoxModel value=new DefaultComboBoxModel();
       this.cmbAjusteMensual.setModel(value);
       value.addElement("No aplica");
       }
       else if (this.cmbAjustedeTasa.getSelectedIndex()==1){
       DefaultComboBoxModel value=new DefaultComboBoxModel();
       this.cmbAjusteMensual.setModel(value);
       value.addElement("2,51%");
       value.addElement("5,67%");
       }
       else{
       DefaultComboBoxModel value=new DefaultComboBoxModel();
       this.cmbAjusteMensual.setModel(value);
       value.addElement("5,09%");
       value.addElement("11,75%");
       }
    }//GEN-LAST:event_cmbAjustedeTasaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if ((!this.txtHasta.getText().equals("")) && (!this.txtDesde.getText().equals(""))){
            if ((!this.txtTasa.getText().equals("")) && (!this.txtSumaAsegurada.getText().equals(""))&&(this.cmbCobertura.getSelectedIndex()!=0)&&(this.cmbProvincia.getItemAt(0).equals("Seleccione"))&&this.cmbProvincia.getSelectedIndex()!=0){
    
        LimpiarTabla();
                
        String Nombre=((Cober)this.cmbCobertura.getSelectedItem()).getNombre();
        double Suma= Double.parseDouble(this.txtSumaAsegurada.getText());
        double Tasa;
        if(this.cmbAjustedeTasa.getSelectedIndex()==0){
        Tasa=Double.parseDouble(this.txtTasa.getText());
        }
        else{
        double ajuste=Double.parseDouble(String.valueOf(this.cmbAjusteMensual.getSelectedItem()).replace("%", "").replace(",", "."));
        Tasa=Double.parseDouble(this.txtTasa.getText())*((ajuste/100)+1);
        }
        String AjusteTasa=String.valueOf(this.cmbAjustedeTasa.getSelectedItem());
        String AjusteMensual=String.valueOf(this.cmbAjusteMensual.getSelectedItem());
        double Prima=((Suma*((Tasa/(double)1000)))/(double)365)*(Double.parseDouble(this.lblDias.getText()));
        
//        Agregar las clausulas
        
        Provincia p =(Provincia)cmbProvincia.getSelectedItem();
        Cobertura c =new Cobertura(Nombre,Suma,Double.parseDouble(this.txtTasa.getText()),AjusteTasa,Prima,((Cober)this.cmbCobertura.getSelectedItem()).getClausulas(),AjusteMensual,p);
        listaCoberturas.add(c);
        for (int i=0;i<listaCoberturas.size();i++){
        MostrarDatos((Cobertura) listaCoberturas.get(i));
                
                }
        MostrarTotales();
        this.txtSumaAsegurada.setText("");
        this.txtTasa.setText("");
        this.cmbCobertura.setSelectedIndex(0);
            }
            else{
            JOptionPane.showMessageDialog(null, "Error faltan datos por ingresar");
            }
            
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Error ingrese las fechas");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbMediodePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMediodePagoActionPerformed
        // TODO add your handling code here:
        if (this.cmbMediodePago.getSelectedIndex()==0){
        this.cmbCuotas.setVisible(false);
        this.lblCuotas.setVisible(false);
        }
        else {
        this.cmbCuotas.setVisible(true);
        this.lblCuotas.setVisible(true);
        }
        MostrarTotales();
    }//GEN-LAST:event_cmbMediodePagoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int borrar=this.TCoberturas.getSelectedRow();
        listaCoberturas.remove(borrar);
        LimpiarTabla();
        
        for (int i=0;i<listaCoberturas.size();i++){
        
        MostrarDatos((Cobertura) listaCoberturas.get(i));
        }
        MostrarTotales();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        if (this.TCoberturas.getSelectedRow()!=-1){
        
        Modificacion mod = new Modificacion(listaCoberturas,this.TCoberturas.getSelectedRow(),Integer.parseInt(this.lblDias.getText()),String.valueOf(this.cmbRamo.getSelectedItem()),this,true);
        mod.setVisible(true);
        
        
       
        LimpiarTabla();
        for (int i=0;i<listaCoberturas.size();i++){
        
        MostrarDatos((Cobertura) listaCoberturas.get(i));
        }
        MostrarTotales();
        
        }
        else{
        JOptionPane.showMessageDialog(null, "Seleccione una cobertura");
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuotasActionPerformed
        // TODO add your handling code here:
        MostrarTotales();
    }//GEN-LAST:event_cmbCuotasActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        PrinterJob printerJob=PrinterJob.getPrinterJob();
        printerJob.setPrintable(this);
        
        if (printerJob.printDialog()){
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void cmbProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProvinciaActionPerformed

    private void cmbResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbResActionPerformed
        // TODO add your handling code here:
        MostrarTotales();
    }//GEN-LAST:event_cmbResActionPerformed

    private void cmbIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIVAActionPerformed
        // TODO add your handling code here:
        MostrarTotales();
    }//GEN-LAST:event_cmbIVAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
    }
    public int print (Graphics graphics,PageFormat pageFormat,int pageIndex){
    if (pageIndex==0){
        Graphics2D g2d=(Graphics2D)graphics;
        
       g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
        this.printAll(graphics);
        
    return Printable.PAGE_EXISTS;
    
    }
    else{
    return Printable.NO_SUCH_PAGE;
    }
    }
    
    public void traerRamos() throws Exception{
        RamoDAO r =new RamoDAO();
        List <Ramo> lista=r.ObtenerRamo();
        
        for (int i=0;i<lista.size();i++){
        Ramo Ra=lista.get(i);
        Object [] objeto =new Object [2];
        objeto[0]=Ra.getNumero();
        objeto[1]=Ra.getNombre();
        }
        
        }
    public void MostrarDatos(Cobertura c){
    mode.insertRow(con, new Object[]{});
    DecimalFormat df=new DecimalFormat("#.##");
    mode.setValueAt(c.getNombre(), con, 0);
    mode.setValueAt(df.format(c.getSumaAsegurada()), con, 1);
    mode.setValueAt(df.format(c.getTasa()), con, 2);
    mode.setValueAt(c.getAjusteTasa(), con, 3);  
    mode.setValueAt(df.format(c.getPrima()), con, 4);
    mode.setValueAt(c.getProvincia().getId(), con, 5);
    totalSumas=totalSumas+c.getSumaAsegurada();
    totalPrimas=totalPrimas+c.getPrima();
    
    
    for (String clau : c.getClausulas()){
        Boolean replicado=false;
     for(int j=0;j<Clausulas.size();j++){
         if(Clausulas.get(j).equals(clau)){
            replicado=true; 
         }
     }
     if(!replicado){
     Clausulas.add(clau);
     }
    
    
    }
    con++;
    
    }
    public void MostrarTotales(){ 
     DecimalFormat df=new DecimalFormat("#.##");   
    this.lblTotalSumas.setText(String.valueOf(df.format(totalSumas)));
    this.lblTotalPrima.setText(String.valueOf(df.format(totalPrimas)));
    for (int i=0;i<listaCoberturas.size();i++){
    CalcularVar((Cobertura)listaCoberturas.get(i));
    }
    
    String Porcentaje=cmbRes.getSelectedItem().toString().replace("%", "");
    double porcentjeRes=Double.parseDouble(Porcentaje);
    
    
    lblResolTotal.setText(df.format(totalPrimas*porcentjeRes/100));
    Subtotal=totalPrimas+totalPrimas*porcentjeRes/100;
    this.lblPrimamasResol.setText(df.format(Subtotal));
    
    CuotaDAO cDAO=new CuotaDAO();
    try {
        List<Cuota> listaC = cDAO.ObtenerCuota();
    
    if(this.cmbMediodePago.getSelectedIndex()==0){
    this.lblPrimaconRecargoFinanciero.setText(df.format(Subtotal));
    
    for (int i=0;i<listaCoberturas.size();i++){
    CalcularRecargoCuotas((Cobertura)listaCoberturas.get(i),1);
    }
    // poner sellado
    }
    else if(this.cmbMediodePago.getSelectedIndex()==1){
    for (int i=0; i<listaC.size();i++){
       if (listaC.get(i).getNumero()==Integer.parseInt(String.valueOf(this.cmbCuotas.getSelectedItem()))){
       
       this.lblPrimaconRecargoFinanciero.setText(df.format(Subtotal*((Double.parseDouble(listaC.get(i).getPorcentaje()))+1)));
       
       
       for (int t=0;t<listaCoberturas.size();t++){
       CalcularRecargoCuotas((Cobertura)listaCoberturas.get(t),Double.parseDouble(listaC.get(i).getPorcentaje())+1);
       }
       
       }
    }
        
    }else{
        if(Integer.parseInt(String.valueOf(this.cmbCuotas.getSelectedItem()))-1!=0){
        for (int i=0; i<listaC.size();i++){
       if (listaC.get(i).getNumero()==Integer.parseInt(String.valueOf(this.cmbCuotas.getSelectedItem()))-1){
       
       this.lblPrimaconRecargoFinanciero.setText(df.format(Subtotal*((Double.parseDouble(listaC.get(i).getPorcentaje()))+1)));
       
       for (int t=0;t<listaCoberturas.size();t++){
       CalcularRecargoCuotas((Cobertura)listaCoberturas.get(t),Double.parseDouble(listaC.get(i).getPorcentaje())+1);
       }
       }
        }
    }
        else{
        this.lblPrimaconRecargoFinanciero.setText(df.format(Subtotal));
        
        for (int t=0;t<listaCoberturas.size();t++){
        CalcularRecargoCuotas((Cobertura)listaCoberturas.get(t),1);
        }
        }
    
    }
    } catch (Exception ex) {
        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    ImpuestoDAO iDAO=new ImpuestoDAO();
    try {
        for (int t=0;t<listaCoberturas.size();t++){
        CalcularImpuestoProv((Cobertura)listaCoberturas.get(t));
        }
        double imp = iDAO.ObtenerProvincia();
        this.lblImpuestos.setText(df.format(Double.parseDouble(this.lblPrimaconRecargoFinanciero.getText().replace(",", "."))*imp));
        this.lblIVA.setText(df.format(Double.parseDouble(this.lblPrimaconRecargoFinanciero.getText().replace(",", "."))*Double.parseDouble(this.cmbIVA.getSelectedItem().toString().replace("%", ""))/100));
        this.lblPremio.setText(df.format(Double.parseDouble(this.lblIVA.getText().replace(",", "."))+Sellado+Double.parseDouble(this.lblImpuestos.getText().replace(",", "."))+Double.parseDouble(this.lblPrimaconRecargoFinanciero.getText().replace(",", "."))));
        String MClausulas="";
        int cont=1;
        for(String clau: Clausulas){
            if(cont<Clausulas.size()){
            MClausulas=MClausulas+clau+"-";
            }
            else{
            MClausulas=MClausulas+clau;
            }
            cont++;
        }
        
        this.lblClausulas.setText(MClausulas);
        this.lblSellados.setText(df.format(Sellado));
        Sellado=0;
    } catch (Exception ex) {
        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
    }
    public void LimpiarTabla(){
        for (int i=0;i<TCoberturas.getRowCount();i++){
        mode.removeRow(i);
        i-=1;
        }
        
    con=0;
    totalSumas=0;
    totalPrimas=0;
    Sellado=0;
    Clausulas.removeAll(Clausulas);
    }
    public void CalcularVar (Cobertura c){
    c.setPrimaConVar(c.getPrima()*(Double.valueOf(this.cmbRes.getSelectedItem().toString().replace("%", ""))/100+1));
    }
    public void CalcularRecargoCuotas (Cobertura c,double recargo){
    c.setPrimaConRecargoCuotas(c.getPrimaConVar()*recargo);
    }
    public void CalcularImpuestoProv (Cobertura c){
    c.setPrimaConImpuestoProv(c.getPrimaConRecargoCuotas()*c.getProvincia().getTasa());
    Sellado=Sellado+c.getPrimaConImpuestoProv();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TCoberturas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbAjusteMensual;
    private javax.swing.JComboBox cmbAjustedeTasa;
    private javax.swing.JComboBox cmbCobertura;
    private javax.swing.JComboBox cmbCuotas;
    private javax.swing.JComboBox cmbIVA;
    private javax.swing.JComboBox cmbMediodePago;
    private javax.swing.JComboBox cmbProvincia;
    private javax.swing.JComboBox cmbRamo;
    private javax.swing.JComboBox cmbRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClausulas;
    private javax.swing.JLabel lblCuotas;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblImpuestos;
    private javax.swing.JLabel lblPremio;
    private javax.swing.JLabel lblPrimaconRecargoFinanciero;
    private javax.swing.JLabel lblPrimamasResol;
    private javax.swing.JLabel lblRamo;
    private javax.swing.JLabel lblResolTotal;
    private javax.swing.JLabel lblSellados;
    private javax.swing.JLabel lblTotalPrima;
    private javax.swing.JLabel lblTotalSumas;
    private javax.swing.JTextField txtAsegurable;
    private javax.swing.JFormattedTextField txtDesde;
    private javax.swing.JFormattedTextField txtHasta;
    private javax.swing.JTextField txtSumaAsegurada;
    private javax.swing.JTextField txtTasa;
    // End of variables declaration//GEN-END:variables
}
